[
  [
    {
      Id: 1,
      Text: "She _____ in the garden for two hours.",
      Marks: 1,
      AnswerId: 12,
      Answers: [
        { Id: 9, Text: "had been planting" },
        { Id: 10, Text: "was planting" },
        { Id: 11, Text: "has been planting" },
        { Id: 12, Text: "had been planting" },
      ],
    },
    {
      Id: 2,
      Text: "They _____ the movie before it started.",
      Marks: 1,
      AnswerId: 19,
      Answers: [
        { Id: 17, Text: "had watched" },
        { Id: 18, Text: "were watching" },
        { Id: 19, Text: "had watched" },
        { Id: 20, Text: "have watched" },
      ],
    },
    {
      Id: 3,
      Text: "He _____ on the project for a week.",
      Marks: 1,
      AnswerId: 28,
      Answers: [
        { Id: 25, Text: "has been working" },
        { Id: 26, Text: "had been working" },
        { Id: 27, Text: "is working" },
        { Id: 28, Text: "had been working" },
      ],
    },
    {
      Id: 4,
      Text: "I _____ English lessons before moving to England.",
      Marks: 1,
      AnswerId: 33,
      Answers: [
        { Id: 32, Text: "had been taking" },
        { Id: 33, Text: "had been taking" },
        { Id: 34, Text: "have taken" },
        { Id: 35, Text: "took" },
      ],
    },
    {
      Id: 5,
      Text: "She _____ for him since morning.",
      Marks: 1,
      AnswerId: 38,
      Answers: [
        { Id: 37, Text: "had been waiting" },
        { Id: 38, Text: "had been waiting" },
        { Id: 39, Text: "has been waiting" },
        { Id: 40, Text: "was waiting" },
      ],
    },
    {
      Id: 6,
      Text: "The students _____ the assignment by 5 PM.",
      Marks: 1,
      AnswerId: 44,
      Answers: [
        { Id: 41, Text: "had finished" },
        { Id: 42, Text: "finished" },
        { Id: 43, Text: "were finishing" },
        { Id: 44, Text: "had finished" },
      ],
    },
    {
      Id: 7,
      Text: "The rain _____ all day yesterday.",
      Marks: 1,
      AnswerId: 50,
      Answers: [
        { Id: 49, Text: "was raining" },
        { Id: 50, Text: "was raining" },
        { Id: 51, Text: "rained" },
        { Id: 52, Text: "has been raining" },
      ],
    },
    {
      Id: 8,
      Text: "By the time they arrived, we _____ dinner.",
      Marks: 1,
      AnswerId: 59,
      Answers: [
        { Id: 57, Text: "ate" },
        { Id: 58, Text: "were eating" },
        { Id: 59, Text: "had eaten" },
        { Id: 60, Text: "had been eating" },
      ],
    },
    {
      Id: 9,
      Text: "He _____ tired because he _____ all day.",
      Marks: 1,
      AnswerId: 65,
      Answers: [
        { Id: 65, Text: "was, had been working" },
        { Id: 66, Text: "was, has been working" },
        { Id: 67, Text: "had been, had been working" },
        { Id: 68, Text: "had been, has been working" },
      ],
    },
    {
      Id: 10,
      Text: "She _____ for a promotion for months.",
      Marks: 1,
      AnswerId: 74,
      Answers: [
        { Id: 73, Text: "was hoping" },
        { Id: 74, Text: "had been hoping" },
        { Id: 75, Text: "hoped" },
        { Id: 76, Text: "has been hoping" },
      ],
    },
    {
      Id: 11,
      Text: "I _____ my car before the race began.",
      Marks: 1,
      AnswerId: 80,
      Answers: [
        { Id: 79, Text: "had repaired" },
        { Id: 80, Text: "had repaired" },
        { Id: 81, Text: "have repaired" },
        { Id: 82, Text: "repaired" },
      ],
    },
    {
      Id: 12,
      Text: "She _____ her novel before the deadline.",
      Marks: 1,
      AnswerId: 88,
      Answers: [
        { Id: 85, Text: "had finished" },
        { Id: 86, Text: "has finished" },
        { Id: 87, Text: "finished" },
        { Id: 88, Text: "had finished" },
      ],
    },
    {
      Id: 13,
      Text: "The kids _____ outside for hours.",
      Marks: 1,
      AnswerId: 93,
      Answers: [
        { Id: 93, Text: "had been playing" },
        { Id: 94, Text: "had been playing" },
        { Id: 95, Text: "were playing" },
        { Id: 96, Text: "played" },
      ],
    },
    {
      Id: 14,
      Text: "They _____ the concert by the time we arrived.",
      Marks: 1,
      AnswerId: 101,
      Answers: [
        { Id: 100, Text: "had finished" },
        { Id: 101, Text: "had finished" },
        { Id: 102, Text: "finished" },
        { Id: 103, Text: "were finishing" },
      ],
    },
    {
      Id: 15,
      Text: "I _____ for that job for months.",
      Marks: 1,
      AnswerId: 108,
      Answers: [
        { Id: 107, Text: "was hoping" },
        { Id: 108, Text: "had been hoping" },
        { Id: 109, Text: "hoped" },
        { Id: 110, Text: "has been hoping" },
      ],
    },
    {
      Id: 16,
      Text: "The project _____ for weeks before they canceled it.",
      Marks: 1,
      AnswerId: 116,
      Answers: [
        { Id: 113, Text: "had been going on" },
        { Id: 114, Text: "was going on" },
        { Id: 115, Text: "has been going on" },
        { Id: 116, Text: "had been going on" },
      ],
    },
    {
      Id: 17,
      Text: "She _____ for the bus for an hour.",
      Marks: 1,
      AnswerId: 121,
      Answers: [
        { Id: 121, Text: "had been waiting" },
        { Id: 122, Text: "had been waiting" },
        { Id: 123, Text: "was waiting" },
        { Id: 124, Text: "waited" },
      ],
    },
    {
      Id: 18,
      Text: "The cake _____ before the party started.",
      Marks: 1,
      AnswerId: 130,
      Answers: [
        { Id: 129, Text: "was baked" },
        { Id: 130, Text: "was baked" },
        { Id: 131, Text: "baked" },
        { Id: 132, Text: "had been baked" },
      ],
    },
    {
      Id: 19,
      Text: "He _____ about his trip before he left.",
      Marks: 1,
      AnswerId: 138,
      Answers: [
        { Id: 137, Text: "had been talking" },
        { Id: 138, Text: "had been talking" },
        { Id: 139, Text: "talked" },
        { Id: 140, Text: "was talking" },
      ],
    },
    {
      Id: 20,
      Text: "They _____ on that project for months.",
      Marks: 1,
      AnswerId: 146,
      Answers: [
        { Id: 145, Text: "had been working" },
        { Id: 146, Text: "had been working" },
        { Id: 147, Text: "were working" },
        { Id: 148, Text: "worked" },
      ],
    },
    {
      Id: 21,
      Text: "I _____ Spanish for a year before moving to Spain.",
      Marks: 1,
      AnswerId: 154,
      Answers: [
        { Id: 153, Text: "had been learning" },
        { Id: 154, Text: "had been learning" },
        { Id: 155, Text: "learned" },
        { Id: 156, Text: "was learning" },
      ],
    },
    {
      Id: 22,
      Text: "She _____ on her novel for a long time.",
      Marks: 1,
      AnswerId: 162,
      Answers: [
        { Id: 161, Text: "had been working" },
        { Id: 162, Text: "had been working" },
        { Id: 163, Text: "has been working" },
        { Id: 164, Text: "was working" },
      ],
    },
    {
      Id: 23,
      Text: "The baby _____ for hours before falling asleep.",
      Marks: 1,
      AnswerId: 171,
      Answers: [
        { Id: 169, Text: "was crying" },
        { Id: 170, Text: "cried" },
        { Id: 171, Text: "had been crying" },
        { Id: 172, Text: "had cried" },
      ],
    },
    {
      Id: 24,
      Text: "They _____ the presentation before the clients arrived.",
      Marks: 1,
      AnswerId: 179,
      Answers: [
        { Id: 177, Text: "had finished" },
        { Id: 178, Text: "were finishing" },
        { Id: 179, Text: "had finished" },
        { Id: 180, Text: "finished" },
      ],
    },
    {
      Id: 25,
      Text: "She _____ for that opportunity for years.",
      Marks: 1,
      AnswerId: 187,
      Answers: [
        { Id: 185, Text: "was hoping" },
        { Id: 186, Text: "hoped" },
        { Id: 187, Text: "had been hoping" },
        { Id: 188, Text: "has been hoping" },
      ],
    },
    {
      Id: 26,
      Text: "The movie _____ for an hour before we got there.",
      Marks: 1,
      AnswerId: 195,
      Answers: [
        { Id: 193, Text: "was playing" },
        { Id: 194, Text: "had played" },
        { Id: 195, Text: "had been playing" },
        { Id: 196, Text: "played" },
      ],
    },
    {
      Id: 27,
      Text: "He _____ for the bus for 30 minutes.",
      Marks: 1,
      AnswerId: 201,
      Answers: [
        { Id: 201, Text: "had been waiting" },
        { Id: 202, Text: "had been waiting" },
        { Id: 203, Text: "was waiting" },
        { Id: 204, Text: "waited" },
      ],
    },
    {
      Id: 28,
      Text: "The book _____ before I started reading it.",
      Marks: 1,
      AnswerId: 210,
      Answers: [
        { Id: 209, Text: "was written" },
        { Id: 210, Text: "had been written" },
        { Id: 211, Text: "had written" },
        { Id: 212, Text: "wrote" },
      ],
    },
    {
      Id: 29,
      Text: "I _____ with my friend on the phone for hours.",
      Marks: 1,
      AnswerId: 217,
      Answers: [
        { Id: 217, Text: "had been talking" },
        { Id: 218, Text: "had been talking" },
        { Id: 219, Text: "talked" },
        { Id: 220, Text: "was talking" },
      ],
    },
    {
      Id: 30,
      Text: "They _____ on that project all night.",
      Marks: 1,
      AnswerId: 225,
      Answers: [
        { Id: 225, Text: "had been working" },
        { Id: 226, Text: "had been working" },
        { Id: 227, Text: "were working" },
        { Id: 228, Text: "worked" },
      ],
    },
    {
      Id: 31,
      Text: "I _____ Spanish for a year before moving to Spain.",
      Marks: 1,
      AnswerId: 235,
      Answers: [
        { Id: 235, Text: "had been learning" },
        { Id: 236, Text: "had been learning" },
        { Id: 237, Text: "learned" },
        { Id: 238, Text: "was learning" },
      ],
    },
    {
      Id: 32,
      Text: "She _____ on her novel for a long time.",
      Marks: 1,
      AnswerId: 246,
      Answers: [
        { Id: 245, Text: "had been working" },
        { Id: 246, Text: "had been working" },
        { Id: 247, Text: "has been working" },
        { Id: 248, Text: "was working" },
      ],
    },
    {
      Id: 33,
      Text: "The baby _____ for hours before falling asleep.",
      Marks: 1,
      AnswerId: 254,
      Answers: [
        { Id: 253, Text: "was crying" },
        { Id: 254, Text: "had been crying" },
        { Id: 255, Text: "cried" },
        { Id: 256, Text: "had cried" },
      ],
    },
    {
      Id: 34,
      Text: "They _____ the presentation before the clients arrived.",
      Marks: 1,
      AnswerId: 262,
      Answers: [
        { Id: 261, Text: "had finished" },
        { Id: 262, Text: "had finished" },
        { Id: 263, Text: "were finishing" },
        { Id: 264, Text: "finished" },
      ],
    },
    {
      Id: 35,
      Text: "She _____ for that opportunity for years.",
      Marks: 1,
      AnswerId: 271,
      Answers: [
        { Id: 269, Text: "was hoping" },
        { Id: 270, Text: "hoped" },
        { Id: 271, Text: "had been hoping" },
        { Id: 272, Text: "has been hoping" },
      ],
    },
    {
      Id: 36,
      Text: "The movie _____ for an hour before we got there.",
      Marks: 1,
      AnswerId: 279,
      Answers: [
        { Id: 277, Text: "was playing" },
        { Id: 278, Text: "had played" },
        { Id: 279, Text: "had been playing" },
        { Id: 280, Text: "played" },
      ],
    },
    {
      Id: 37,
      Text: "He _____ for the bus for 30 minutes.",
      Marks: 1,
      AnswerId: 285,
      Answers: [
        { Id: 285, Text: "had been waiting" },
        { Id: 286, Text: "had been waiting" },
        { Id: 287, Text: "was waiting" },
        { Id: 288, Text: "waited" },
      ],
    },
    {
      Id: 38,
      Text: "The book _____ before I started reading it.",
      Marks: 1,
      AnswerId: 292,
      Answers: [
        { Id: 291, Text: "was written" },
        { Id: 292, Text: "had been written" },
        { Id: 293, Text: "had written" },
        { Id: 294, Text: "wrote" },
      ],
    },
    {
      Id: 39,
      Text: "I _____ with my friend on the phone for hours.",
      Marks: 1,
      AnswerId: 300,
      Answers: [
        { Id: 299, Text: "had been talking" },
        { Id: 300, Text: "had been talking" },
        { Id: 301, Text: "talked" },
        { Id: 302, Text: "was talking" },
      ],
    },
    {
      Id: 40,
      Text: "They _____ on that project all night.",
      Marks: 1,
      AnswerId: 308,
      Answers: [
        { Id: 307, Text: "had been working" },
        { Id: 308, Text: "had been working" },
        { Id: 309, Text: "were working" },
        { Id: 310, Text: "worked" },
      ],
    },
    {
      Id: 41,
      Text: "I _____ Spanish for a year before moving to Spain.",
      Marks: 1,
      AnswerId: 318,
      Answers: [
        { Id: 317, Text: "had been learning" },
        { Id: 318, Text: "had been learning" },
        { Id: 319, Text: "learned" },
        { Id: 320, Text: "was learning" },
      ],
    },
    {
      Id: 42,
      Text: "She _____ on her novel for a long time.",
      Marks: 1,
      AnswerId: 327,
      Answers: [
        { Id: 325, Text: "had been working" },
        { Id: 326, Text: "has been working" },
        { Id: 327, Text: "had been working" },
        { Id: 328, Text: "was working" },
      ],
    },
    {
      Id: 43,
      Text: "The baby _____ for hours before falling asleep.",
      Marks: 1,
      AnswerId: 335,
      Answers: [
        { Id: 333, Text: "was crying" },
        { Id: 334, Text: "cried" },
        { Id: 335, Text: "had been crying" },
        { Id: 336, Text: "had cried" },
      ],
    },
    {
      Id: 44,
      Text: "They _____ the presentation before the clients arrived.",
      Marks: 1,
      AnswerId: 343,
      Answers: [
        { Id: 341, Text: "had finished" },
        { Id: 342, Text: "were finishing" },
        { Id: 343, Text: "had finished" },
        { Id: 344, Text: "finished" },
      ],
    },
    {
      Id: 45,
      Text: "She _____ for that opportunity for years.",
      Marks: 1,
      AnswerId: 351,
      Answers: [
        { Id: 349, Text: "was hoping" },
        { Id: 350, Text: "hoped" },
        { Id: 351, Text: "had been hoping" },
        { Id: 352, Text: "has been hoping" },
      ],
    },
    {
      Id: 46,
      Text: "The movie _____ for an hour before we got there.",
      Marks: 1,
      AnswerId: 359,
      Answers: [
        { Id: 357, Text: "was playing" },
        { Id: 358, Text: "had played" },
        { Id: 359, Text: "had been playing" },
        { Id: 360, Text: "played" },
      ],
    },
    {
      Id: 47,
      Text: "He _____ for the bus for 30 minutes.",
      Marks: 1,
      AnswerId: 365,
      Answers: [
        { Id: 365, Text: "had been waiting" },
        { Id: 366, Text: "had been waiting" },
        { Id: 367, Text: "was waiting" },
        { Id: 368, Text: "waited" },
      ],
    },
    {
      Id: 48,
      Text: "The book _____ before I started reading it.",
      Marks: 1,
      AnswerId: 374,
      Answers: [
        { Id: 373, Text: "was written" },
        { Id: 374, Text: "had been written" },
        { Id: 375, Text: "had written" },
        { Id: 376, Text: "wrote" },
      ],
    },
    {
      Id: 49,
      Text: "I _____ with my friend on the phone for hours.",
      Marks: 1,
      AnswerId: 382,
      Answers: [
        { Id: 381, Text: "had been talking" },
        { Id: 382, Text: "had been talking" },
        { Id: 383, Text: "talked" },
        { Id: 384, Text: "was talking" },
      ],
    },
    {
      Id: 50,
      Text: "They _____ on that project all night.",
      Marks: 1,
      AnswerId: 390,
      Answers: [
        { Id: 389, Text: "had been working" },
        { Id: 390, Text: "had been working" },
        { Id: 391, Text: "were working" },
        { Id: 392, Text: "worked" },
      ],
    },
  ],
];
